from checklist_engine import (
    calculate_risk_counts,
    calculate_governance_score,
    get_overall_governance_assessment
)


def generate_markdown_report(ai_system_type, checklist):
    high_count, medium_count, low_count = calculate_risk_counts(checklist)
    governance_score = calculate_governance_score(checklist)
    overall_assessment = get_overall_governance_assessment(high_count, medium_count)

    report = "# AI Governance Checklist Report\n\n"

    report += "## Executive Summary\n\n"
    report += f"- **AI system type:** {ai_system_type}\n"
    report += f"- **Total controls generated:** {len(checklist)}\n"
    report += f"- **High-risk controls:** {high_count}\n"
    report += f"- **Medium-risk controls:** {medium_count}\n"
    report += f"- **Low-risk controls:** {low_count}\n"
    report += f"- **Governance score:** {governance_score}\n"
    report += f"- **Overall assessment:** {overall_assessment}\n\n"

    report += "## Governance Risk Overview\n\n"
    report += (
        "This section summarizes the governance attention required for the selected AI system type. "
        "Higher scores indicate that stronger governance controls, documentation, review mechanisms "
        "and internal accountability measures should be implemented before deployment or operational use.\n\n"
    )

    report += "## Governance Checklist\n\n"
    report += "| Category | Risk Level | Priority | Owner |\n"
    report += "|---|---|---|---|\n"

    for control in checklist:
        report += (
            f"| {control['category']} | "
            f"{control['risk_level']} | "
            f"{control['priority']} | "
            f"{control['owner']} |\n"
        )

    report += "\n"

    report += "## Detailed Recommended Controls\n\n"

    for index, control in enumerate(checklist, start=1):
        report += f"### Control {index}: {control['category']}\n\n"
        report += f"- **Risk Level:** {control['risk_level']}\n"
        report += f"- **Priority:** {control['priority']}\n"
        report += f"- **Owner:** {control['owner']}\n"
        report += f"- **Control Objective:** {control['control_objective']}\n"
        report += f"- **Recommended Control:** {control['recommended_control']}\n\n"

    report += "## Strategic Use\n\n"
    report += (
        "This report can support early-stage AI governance review by helping legal, compliance, "
        "product, data and business teams identify key control areas before deploying or scaling "
        "an AI system. It is designed as an operational checklist rather than a formal regulatory "
        "compliance certification.\n\n"
    )

    report += "## Disclaimer\n\n"
    report += (
        "This report is generated by a rule-based prototype for educational and portfolio purposes only. "
        "It does not provide legal advice, regulatory advice or compliance certification. "
        "Users should consult qualified professionals before making legal, regulatory or business decisions.\n"
    )

    return report